etcher: app: i18n: Translation: Update zh-TW strings
balena-io/etcher pull request #4004
Opened 2023-02-02 13:45 UTC by bluehomewu

* Improve translate.
* Sync layout with English strings ts file.

Signed-off-by: Edward Wu <bluehome.wu@gmail.com>

Hello, all.
The word usage of the translation strings in the past are in the style of China rather than Taiwan.
I'm Taiwanese, who works on Android and Translation projects.

2023-02-02 14:06 UTC, pan93412 requested changes
另外：

- `failedTarget`, `failedRetry` 翻譯腔嚴重

2023-02-02 14:06 UTC, pan93412 commented on lib/gui/app/i18n/zh-TW.ts
>  			unsupportedProtocol: '不支持的協議',
協議 → 通訊協定

2023-02-02 14:06 UTC, pan93412 commented on lib/gui/app/i18n/zh-TW.ts
> +			windowsImage: '這可能是 Windows 系統映像',
「映像」改「映像檔」

2023-02-02 14:06 UTC, pan93412 commented on lib/gui/app/i18n/zh-TW.ts
> +			errorOpen: '打開來源映像時出錯',
「映像」改「映像檔」

2023-02-02 14:06 UTC, pan93412 commented on lib/gui/app/i18n/zh-TW.ts
> +			fromURL: '從網路燒錄',
在線地址 = 網址

2023-02-02 14:06 UTC, pan93412 commented on lib/gui/app/i18n/zh-TW.ts
> +			clone: '複製磁碟',
注意不要混淆 copy 跟 clone。這裡可翻譯成「再製」。

2023-02-02 14:06 UTC, pan93412 commented on lib/gui/app/i18n/zh-TW.ts
> +			image: '映像訊息',
「映像」改「映像檔」

2023-02-02 14:06 UTC, pan93412 commented on lib/gui/app/i18n/zh-TW.ts
> +			image: '映像訊息',
信息 (information) → 資訊

2023-02-02 14:06 UTC, pan93412 commented on lib/gui/app/i18n/zh-TW.ts
> +			osImages: '系統映像格式',
「映像」改「映像檔」

2023-02-02 14:06 UTC, pan93412 commented on lib/gui/app/i18n/zh-TW.ts
> +			enterValidURL: '請輸入一個正確的網址',
部分中文語境下可以省略「一個」。

2023-02-02 14:06 UTC, pan93412 commented on lib/gui/app/i18n/zh-TW.ts
>  			select: '選定 {{select}}',
「選取」會不會比較好？

2023-02-02 14:06 UTC, pan93412 commented on lib/gui/app/i18n/zh-TW.ts
> +			systemDriveDanger: '選擇系統分區很危險，因為這將會刪除你的系統！',
分區 (partition) → 分割區

2023-02-02 14:06 UTC, pan93412 commented on lib/gui/app/i18n/zh-TW.ts
> +			largeDriveWarningMsg: '您確定所選磁碟不是儲存磁碟嗎？',
存儲磁盤根據上下文，應該是指「儲存資料的磁碟」。不過建議根據原文進行調整。

2023-02-02 14:06 UTC, pan93412 commented on lib/gui/app/i18n/zh-TW.ts
> +			systemDriveWarning: '您將要格式化系統分區',
分區 (partition) → 分割區

2023-02-02 14:06 UTC, pan93412 commented on lib/gui/app/i18n/zh-TW.ts
> +			systemDriveWarningMsg: '您確定要燒錄到系統分區嗎？',
分區 (partition) → 分割區

2023-02-02 14:06 UTC, pan93412 commented on lib/gui/app/i18n/zh-TW.ts
> +			moreInfo: '更多訊息',
信息 (information) → 資訊

2023-02-02 14:06 UTC, pan93412 commented on lib/gui/app/i18n/zh-TW.ts
> +				'透過將映像大小除以燒錄時間來計算速度。\n由於我們能夠跳過未使用的部分，因此具有EXT分區的磁碟映像燒錄速度更快。',
「映像」改「映像檔」

2023-02-02 14:06 UTC, pan93412 commented on lib/gui/app/i18n/zh-TW.ts
> +				'透過將映像大小除以燒錄時間來計算速度。\n由於我們能夠跳過未使用的部分，因此具有EXT分區的磁碟映像燒錄速度更快。',
中英建議補間。

2023-02-02 14:06 UTC, pan93412 commented on lib/gui/app/i18n/zh-TW.ts
>  			errorReporting: '匿名地向 balena.io 報告運行錯誤和使用統計',
匿名向 balena.io 回報程式錯誤和使用統計資料

2023-02-02 14:06 UTC, pan93412 commented on lib/gui/app/i18n/zh-TW.ts
> +			systemInformation: '系統訊息',
信息 (information) → 資訊

2023-02-02 14:06 UTC, pan93412 commented on lib/gui/app/i18n/zh-TW.ts
> +				'修改原始映像上未分配的空間（在 ext 類型分區中）',
分區 (partition) → 分割區

2023-02-02 14:06 UTC, pan93412 commented on lib/gui/app/i18n/zh-TW.ts
> +				'修改原始映像上未分配的空間（在 ext 類型分區中）',
「映像」改「映像檔」

2023-02-02 14:06 UTC, pan93412 commented on lib/gui/app/i18n/zh-TW.ts
> +				'修改原始映像上未分配的空間（在 ext 類型分區中）',
詞彙不統一：之前 allocate 被翻譯成「配置」，現在卻翻譯成「分配」。

2023-02-02 14:06 UTC, pan93412 commented on lib/gui/app/i18n/zh-TW.ts
> +			window: '窗口',
視窗

2023-02-02 14:06 UTC, pan93412 commented on lib/gui/app/i18n/zh-TW.ts
> +			issue: '提交一個 issue',
提交 issue 就好

2023-02-02 14:06 UTC, pan93412 commented on lib/gui/app/i18n/zh-TW.ts
> +			hideOthers: '隱藏其它窗口',
視窗

2023-02-02 14:11 UTC, pan93412 reviewed
不是特別主要的建議。

2023-02-02 14:11 UTC, pan93412 commented on lib/gui/app/i18n/zh-TW.ts
> +		reallyExit: '真的要現在退出 Etcher 嗎？',
退出 → 結束

2023-02-02 14:11 UTC, pan93412 commented on lib/gui/app/i18n/zh-TW.ts
> +		yesExit: '是的，可以退出',
退出 → 結束

2023-02-02 14:11 UTC, pan93412 commented on lib/gui/app/i18n/zh-TW.ts
>  			sizeNotRecommended: '大小不推薦',
通常 recommend 微軟習慣是翻「建議」

2023-02-02 14:11 UTC, pan93412 commented on lib/gui/app/i18n/zh-TW.ts
> +			openError: '打開 {{source}} 時出錯。\n\n錯誤訊息： {{error}}',
- MS/Google style: 開啟
- Apple style: 打開 (維持原樣)

2023-02-02 14:11 UTC, pan93412 commented on lib/gui/app/i18n/zh-TW.ts
> +			openError: '打開 {{source}} 時出錯。\n\n錯誤訊息： {{error}}',
出錯 → 發生錯誤

2023-02-02 14:11 UTC, pan93412 commented on lib/gui/app/i18n/zh-TW.ts
> +			openError: '打開 {{source}} 時出錯。\n\n錯誤訊息： {{error}}',
信息 (information) → 資訊

2023-02-02 14:11 UTC, pan93412 commented on lib/gui/app/i18n/zh-TW.ts
>  			change: '更改',
- MS style: 變更
- Alternative style: 更改 (維持原樣)

2023-02-02 14:11 UTC, pan93412 commented on lib/gui/app/i18n/zh-TW.ts
>  			partitionTable: '找不到分區表',
分區表 → 分割表

2023-02-02 14:11 UTC, pan93412 commented on lib/gui/app/i18n/zh-TW.ts
>  			openInBrowser: 'Etcher 會在瀏覽器中打開 {{link}}',
- MS/Google style: 開啟
- Apple style: 打開 (維持原樣)

2023-02-02 14:11 UTC, pan93412 commented on lib/gui/app/i18n/zh-TW.ts
>  			changeTarget: '改變目標',
詞彙不一致。上面使用「更改」，這裡應當也使用「更改」。

2023-02-02 14:11 UTC, pan93412 commented on lib/gui/app/i18n/zh-TW.ts
> +			devTool: '打開開發者工具',
- MS/Google style: 開啟
- Apple style: 打開 (維持原樣)

2023-02-02 14:11 UTC, pan93412 commented on lib/gui/app/i18n/zh-TW.ts
> +			quit: '退出 Etcher',
退出 → 結束

2023-02-02 14:11 UTC, pan93412 commented on lib/gui/app/i18n/zh-TW.ts
> +			help: '協助',
說明 / 輔助說明 / 協助 均可參考。

2023-02-02 15:05 UTC, bluehomewu commented on lib/gui/app/i18n/zh-TW.ts
> +				'看起來這不是一個可啟動的{{type}}。\n\n這個{{type}}似乎不包含分區表，因此您的設備可能無法識別或無法正確啟動。',
這個個人認為沒有必要

2023-02-02 15:06 UTC, bluehomewu commented on lib/gui/app/i18n/zh-TW.ts
> +				'看起來這不是一個可啟動的{{type}}。\n\n這個{{type}}似乎不包含分區表，因此您的設備可能無法識別或無法正確啟動。',
設備 / 裝置 我覺得其實沒有太大的問題

2023-02-02 16:44 UTC, pan93412 requested changes

2023-02-02 16:44 UTC, pan93412 commented on lib/gui/app/i18n/zh-TW.ts
> +			systemInformation: '系統訊息',
這裡原文是 information，所以確實應該用「資訊」。「信息」混淆了「訊息」(message) 和「資訊」(information)，而選擇「訊息」會導致意思偏差。

src: System Information

2023-02-02 16:44 UTC, pan93412 commented on lib/gui/app/i18n/zh-TW.ts
> +			moreInfo: '更多訊息',
這裡原文是 info，所以確實應該用「資訊」。「信息」混淆了「訊息」(message) 和「資訊」(information)，而選擇「訊息」會導致意思偏差。

src: more info

2023-02-02 16:44 UTC, pan93412 commented on lib/gui/app/i18n/zh-TW.ts
> +			fromURL: '從網路燒錄',
這裡原文是 url，所以確實應該用「網址」。「網路」只有留下 Internet / Network 的意思，而缺少了「位址」(address) 的概念。

src: Flash from URL

2023-02-06 11:12 UTC, mcraa commented
Thanks for the updates, I hope it is understandable it takes a bit of time to double check this, if we don't just use google translate.
In the meantime can you please update the commit message to make the CI happy?
Something like:
```
patch: app: i18n: Translation: Update zh-TW strings

* Improve translate.
* Sync layout with English strings ts file.

Signed-off-by: Edward Wu <bluehome.wu@gmail.com>
```
would work, notice the `patch:` at the beginning, it is used to generate versioning.

2023-02-06 12:07 UTC, bluehomewu commented
> Thanks for the updates, I hope it is understandable it takes a bit of time to double check this, if we don't just use google translate. In the meantime can you please update the commit message to make the CI happy? Something like:
> 
> ```
> patch: app: i18n: Translation: Update zh-TW strings
> 
> * Improve translate.
> * Sync layout with English strings ts file.
> 
> Signed-off-by: Edward Wu <bluehome.wu@gmail.com>
> ```
> 
> would work, notice the `patch:` at the beginning, it is used to generate versioning.

Thanks for reminding commit message infomation, and also fix @pan93412 proposed issue.

2023-02-12 01:33 UTC, bluehomewu commented
Notes: Update with rebase.
rebase with upstream to 1.15.5

2023-02-12 01:33 UTC, bluehomewu commented
@aethernet @mcraa plz check

2023-02-13 11:21 UTC, mcraa approved these changes

2023-02-13 11:22 UTC, merged